POST http://localhost:8080/api/persons
Content-Type: application/json

{
  "name": "Foo Bar",
  "number": "10-22-334455"
}

###
POST http://localhost:8080/api/persons
Content-Type: application/json

{
  "name": "Foo Bar"
}

###
POST http://localhost:8080/api/persons
Content-Type: application/json

{
  "number": "555-666-777"
}

###
POST http://localhost:8080/api/persons
Content-Type: application/json

{
  "name": "Bar zoo",
  "number": "09-1234556"
}