POST http://localhost:8080/api/persons
Content-Type: application/json

{
  "name": "Foo Bar",
  "number": "12-345-678"
}

###
POST http://localhost:8080/api/persons
Content-Type: application/json

{
  "name": "Foo Bar"
}

###
POST http://localhost:8080/api/persons
Content-Type: application/json

{
  "number": "555-666-777"
}

###
POST http://localhost:8080/api/persons
Content-Type: application/json

{
  "name": "Bar zoo",
  "number": "57-88-75-320"
}