GET http://localhost:8080/api/blogs

###
POST http://localhost:8080/api/blogs HTTP/1.1
Content-Type: application/json

{
  "title": "Express good practices",
  "author": "Foo Bar",
  "url": "https://fullstackopen.com/en",
  "likes": 100
}

###
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "username": "nikoresu",
  "name": "Nicolás Montañez",
  "password": "Sekretp@ss4321"
}

###
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "username": "standUser",
  "name": "Foo Bar",
  "password": "mypass2023"
}